"use client";

import { Download, X } from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";

import type { EventGalleryItem } from "@/types/event";

export default function EventGallery({ items, allowDownloads, onOpen, onDownload }: { items: EventGalleryItem[]; allowDownloads: boolean; onOpen: () => void; onDownload: () => void }) {
  const [visible, setVisible] = useState(12); const [active, setActive] = useState<number | null>(null); const sentinel = useRef<HTMLDivElement>(null); const touch = useRef(0);
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) setVisible((v) => Math.min(v + 12, items.length)); }, { rootMargin: "300px" }); observer.observe(node); return () => observer.disconnect(); }, [items.length]);
  const move = useCallback((direction: number) => setActive((current) => current === null ? null : (current + direction + items.length) % items.length), [items.length]);
  useEffect(() => { if (active === null) return; onOpen(); const key = (e: KeyboardEvent) => { if (e.key === "Escape") setActive(null); if (e.key === "ArrowRight") move(1); if (e.key === "ArrowLeft") move(-1); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [active, move, onOpen]);
  const selected = active === null ? null : items[active];
  return <section className="event-section"><div className="text-center"><p className="event-kicker">Memories</p><h2 className="event-heading">Captured forever</h2></div><div className="mt-10 columns-1 gap-3 sm:columns-2 lg:columns-3">{items.slice(0,visible).map((item,index) => <button key={item.id} onClick={() => setActive(index)} className="mb-3 block w-full overflow-hidden bg-black/10 text-left" aria-label={`Open ${item.caption || "gallery item"}`}>{item.type === "video" ? <video src={item.url} className="h-auto w-full" preload="metadata" muted playsInline /> : <Image src={item.url} alt={item.caption || "Event memory"} width={1200} height={900} sizes="(max-width: 640px) 100vw, 33vw" className="h-auto w-full transition duration-700 hover:scale-[1.02]" />}</button>)}</div><div ref={sentinel} className="h-1" />{selected && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 p-4" onTouchStart={(e) => { touch.current = e.touches[0].clientX; }} onTouchEnd={(e) => { const delta = e.changedTouches[0].clientX - touch.current; if (Math.abs(delta) > 50) move(delta < 0 ? 1 : -1); }}><button onClick={() => setActive(null)} className="absolute right-5 top-5 z-10 p-3 text-white" aria-label="Close"><X /></button>{allowDownloads && selected.downloadEnabled && <a href={selected.url} download onClick={onDownload} className="absolute left-5 top-5 z-10 flex items-center gap-2 border border-white/20 px-4 py-2 text-sm text-white"><Download className="h-4 w-4" /> Download</a>}{selected.type === "video" ? <video src={selected.url} controls autoPlay className="max-h-[88vh] max-w-[94vw]" /> : <Image src={selected.url} alt={selected.caption || "Event memory"} width={1800} height={1200} sizes="94vw" className="max-h-[88vh] w-auto object-contain" priority />}</div>}</section>;
}
