"use client";

import { ArrowDown, ArrowUp, Eye, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import EventAdminNav from "@/components/events/admin/EventAdminNav";
import { EVENT_SECTIONS, EVENT_THEMES, EVENT_TYPES, createEmptyEvent, slugify } from "@/lib/events/config";
import { getEvent, saveEvent } from "@/lib/events/events";
import type { EventInput, EventTimelineItem } from "@/types/event";

const field="field-surface w-full px-4 py-3";
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="border border-white/10 bg-white/[.025] p-5 sm:p-6"><h2 className="font-serif text-2xl">{title}</h2><div className="mt-6 grid gap-5">{children}</div></section>}
function Label({name,children}:{name:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm text-white/60"><span>{name}</span>{children}</label>}

export default function EventBuilder({eventId}:{eventId?:string}){
  const router=useRouter();const[data,setData]=useState<EventInput>(createEmptyEvent());const[loading,setLoading]=useState(Boolean(eventId));const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
  useEffect(()=>{if(!eventId)return;getEvent(eventId).then((e)=>{if(e){const{id:_id,createdAt:_c,updatedAt:_u,publishedAt:_p,...input}=e;setData(input);}setLoading(false);}).catch(()=>setLoading(false));},[eventId]);
  const set=<K extends keyof EventInput>(key:K,value:EventInput[K])=>setData((current)=>({...current,[key]:value}));
  const timeline=(index:number,patch:Partial<EventTimelineItem>)=>set("timeline",data.timeline.map((x,i)=>i===index?{...x,...patch}:x));
  const move=(index:number,direction:number)=>{const next=[...data.timeline];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];set("timeline",next);};
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const id=await saveEvent(data,eventId);setMessage("Event saved successfully.");if(!eventId)router.replace(`/admin/events/${id}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Unable to save event.");}finally{setSaving(false);}}
  if(loading)return <div className="flex items-center gap-2 text-white/50"><Loader2 className="h-4 w-4 animate-spin"/>Loading event</div>;
  return <form onSubmit={submit} className="space-y-6">{eventId&&<EventAdminNav id={eventId}/>}<div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[var(--accent-gold)]">Event Builder</p><h1 className="mt-2 font-serif text-4xl">{eventId?data.title||"Untitled event":"Create an experience"}</h1></div><div className="flex gap-2">{eventId&&data.slug&&<a href={`/events/${data.slug}`} target="_blank" className="flex items-center gap-2 border border-white/10 px-4 py-3 text-sm"><Eye className="h-4 w-4"/>Preview</a>}<button disabled={saving} className="flex items-center gap-2 bg-[var(--accent-gold)] px-5 py-3 text-sm text-black disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save</button></div></div>{message&&<p className="border border-[var(--accent-gold)]/30 bg-[var(--accent-gold)]/10 px-4 py-3 text-sm">{message}</p>}
  <Panel title="General"><div className="grid gap-5 sm:grid-cols-2"><Label name="Title"><input required value={data.title} onChange={e=>{set("title",e.target.value);if(!eventId)set("slug",slugify(e.target.value));}} className={field}/></Label><Label name="Slug"><div className="flex items-center"><span className="border border-r-0 border-white/10 px-3 py-[15px] text-white/35">/events/</span><input required value={data.slug} onChange={e=>set("slug",slugify(e.target.value))} className={field}/></div></Label><Label name="Event type"><select value={data.eventType} onChange={e=>set("eventType",e.target.value)} className={field}>{EVENT_TYPES.map(x=><option key={x}>{x}</option>)}</select></Label><Label name="Theme"><select value={data.theme} onChange={e=>set("theme",e.target.value)} className={field}>{Object.entries(EVENT_THEMES).map(([id,t])=><option value={id} key={id}>{t.label}</option>)}</select></Label><Label name="Status"><select value={data.status} onChange={e=>set("status",e.target.value as EventInput["status"])} className={field}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Label><Label name="Background accent (optional CSS color)"><input value={data.backgroundAccent} onChange={e=>set("backgroundAccent",e.target.value)} placeholder="#c6a46c" className={field}/></Label></div><div className="grid gap-5 sm:grid-cols-2"><Label name="Cover image URL"><input value={data.coverImage} onChange={e=>set("coverImage",e.target.value)} className={field}/></Label><Label name="Hero image URL"><input value={data.heroImage} onChange={e=>set("heroImage",e.target.value)} className={field}/></Label></div></Panel>
  <Panel title="Event details"><div className="grid gap-5 sm:grid-cols-3"><Label name="Date"><input type="date" value={data.eventDate} onChange={e=>set("eventDate",e.target.value)} className={field}/></Label><Label name="Time"><input type="time" value={data.eventTime} onChange={e=>set("eventTime",e.target.value)} className={field}/></Label><Label name="End date"><input type="date" value={data.endDate} onChange={e=>set("endDate",e.target.value)} className={field}/></Label></div><div className="grid gap-5 sm:grid-cols-2"><Label name="Venue"><input value={data.venue} onChange={e=>set("venue",e.target.value)} className={field}/></Label><Label name="Google Maps URL"><input type="url" value={data.mapsUrl} onChange={e=>set("mapsUrl",e.target.value)} className={field}/></Label></div><Label name="Address"><textarea value={data.address} onChange={e=>set("address",e.target.value)} className={`${field} min-h-24`}/></Label><Label name="Host names"><input value={data.hostNames} onChange={e=>set("hostNames",e.target.value)} className={field}/></Label><Label name="Description"><textarea value={data.description} onChange={e=>set("description",e.target.value)} className={`${field} min-h-28`}/></Label><div className="grid gap-5 sm:grid-cols-2"><Label name="Dress code"><input value={data.dressCode} onChange={e=>set("dressCode",e.target.value)} className={field}/></Label><Label name="Hashtag"><input value={data.hashtag} onChange={e=>set("hashtag",e.target.value)} className={field}/></Label></div><Label name="Story"><textarea value={data.story} onChange={e=>set("story",e.target.value)} className={`${field} min-h-32`}/></Label><Label name="Family"><textarea value={data.family} onChange={e=>set("family",e.target.value)} className={`${field} min-h-28`}/></Label></Panel>
  <Panel title="Timeline"><div className="space-y-3">{data.timeline.map((item,index)=><div key={item.id} className="grid gap-3 border border-white/10 p-4 md:grid-cols-[8rem_1fr_1fr_auto]"><input type="time" value={item.time} onChange={e=>timeline(index,{time:e.target.value})} className={field}/><input placeholder="Moment" value={item.title} onChange={e=>timeline(index,{title:e.target.value})} className={field}/><input placeholder="Description" value={item.description} onChange={e=>timeline(index,{description:e.target.value})} className={field}/><div className="flex"><button type="button" onClick={()=>move(index,-1)} className="p-2"><ArrowUp className="h-4 w-4"/></button><button type="button" onClick={()=>move(index,1)} className="p-2"><ArrowDown className="h-4 w-4"/></button><button type="button" onClick={()=>set("timeline",data.timeline.filter((_,i)=>i!==index))} className="p-2 text-red-300"><Trash2 className="h-4 w-4"/></button></div></div>)}</div><button type="button" onClick={()=>set("timeline",[...data.timeline,{id:crypto.randomUUID(),time:"",title:"",description:""}])} className="flex w-fit items-center gap-2 border border-white/10 px-4 py-3 text-sm"><Plus className="h-4 w-4"/>Add moment</button></Panel>
  <Panel title="Sections"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{EVENT_SECTIONS.map(({key,label})=><label key={key} className="flex items-center justify-between border border-white/10 px-4 py-3 text-sm"><span>{label}</span><input type="checkbox" checked={data.sections[key]} onChange={e=>set("sections",{...data.sections,[key]:e.target.checked})}/></label>)}</div></Panel>
  <Panel title="SEO & sharing"><Label name="SEO title"><input value={data.seoTitle} onChange={e=>set("seoTitle",e.target.value)} className={field}/></Label><Label name="SEO description"><textarea value={data.seoDescription} onChange={e=>set("seoDescription",e.target.value)} className={`${field} min-h-24`}/></Label><Label name="OpenGraph image URL"><input value={data.openGraphImage} onChange={e=>set("openGraphImage",e.target.value)} className={field}/></Label><div className="grid gap-3 sm:grid-cols-3"><label className="flex gap-3 text-sm"><input type="checkbox" checked={data.settings.allowDownloads} onChange={e=>set("settings",{...data.settings,allowDownloads:e.target.checked})}/>Allow downloads</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={data.settings.allowGuestbook} onChange={e=>set("settings",{...data.settings,allowGuestbook:e.target.checked})}/>Allow guestbook</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={data.settings.showShare} onChange={e=>set("settings",{...data.settings,showShare:e.target.checked})}/>Show sharing</label></div></Panel></form>;
}
